### Makefile --- 

## Author: shell@shell-deb.shdiv.qizhitech.com
## Version: $Id: Makefile,v 0.0 2012/10/23 08:40:13 shell Exp $
## Keywords: 
## X-URL: 

all:

24point-go:
	go build 24point-go.go

go: 24point-go
	time ./24point-go

lua:
	time lua 24point.lua

python:
	time python 24point.py

### Makefile ends here
